// 1) Функція, що рендерить розмітку для 1 картки - Ярослав Михайлов;

//Виклик шаблону hbs:
import cardMarkup from '../../templates/film-card.hbs';

const Handlebars = require('handlebars');

const BASEIMGURL = 'https://image.tmdb.org/t/p/w500';
const response = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
      id: 505642,
      title: 'Black Panther: Wakanda Forever',
      original_language: 'en',
      original_title: 'Black Panther: Wakanda Forever',
      overview:
        'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
      //   poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 2791.083,
      release_date: '2022-11-09',
      video: false,
      vote_average: 7.6,
      vote_count: 2091,
    },
    {
      adult: false,
      backdrop_path: '/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg',
      id: 536554,
      title: 'M3GAN',
      original_language: 'en',
      original_title: 'M3GAN',
      overview:
        "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
      poster_path: '/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg',
      media_type: 'movie',
      genre_ids: [878, 27, 35],
      popularity: 3280.657,
      release_date: '2022-12-28',
      video: false,
      vote_average: 7.547,
      vote_count: 1161,
    },
    {
      adult: false,
      backdrop_path: '/gwRMwljwHoNCyyJVgMA2XC4qPUU.jpg',
      id: 615777,
      title: 'Babylon',
      original_language: 'en',
      original_title: 'Babylon',
      overview:
        "A tale of outsized ambition and outrageous excess, tracing the rise and fall of multiple characters in an era of unbridled decadence and depravity during Hollywood's transition from silent films and to sound films in the late 1920s.",
      poster_path: '/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg',
      media_type: 'movie',
      genre_ids: [18, 35],
      popularity: 641.941,
      release_date: '2022-12-22',
      video: false,
      vote_average: 7.8,
      vote_count: 657,
    },
    {
      adult: false,
      backdrop_path: '/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
      id: 76600,
      title: 'Avatar: The Way of Water',
      original_language: 'en',
      original_title: 'Avatar: The Way of Water',
      overview:
        'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
      poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
      media_type: 'movie',
      genre_ids: [878, 12, 28],
      popularity: 1892.43,
      release_date: '2022-12-14',
      video: false,
      vote_average: 7.745,
      vote_count: 4923,
    },
    {
      adult: false,
      backdrop_path: '/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg',
      id: 758009,
      title: 'Shotgun Wedding',
      original_language: 'en',
      original_title: 'Shotgun Wedding',
      overview:
        'Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.',
      poster_path: '/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg',
      media_type: 'movie',
      genre_ids: [28, 10749, 35],
      popularity: 856.822,
      release_date: '2022-12-28',
      video: false,
      vote_average: 6.3,
      vote_count: 167,
    },
    {
      adult: false,
      backdrop_path: '/faXT8V80JRhnArTAeYXz0Eutpv9.jpg',
      id: 315162,
      title: 'Puss in Boots: The Last Wish',
      original_language: 'en',
      original_title: 'Puss in Boots: The Last Wish',
      overview:
        'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
      poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
      media_type: 'movie',
      genre_ids: [16, 12, 35, 10751, 14],
      popularity: 4471.915,
      release_date: '2022-12-07',
      video: false,
      vote_average: 8.6,
      vote_count: 3105,
    },
    {
      adult: false,
      backdrop_path: '/96SADhPnkXnVN3KaRKsDeBovLcm.jpg',
      id: 877703,
      title: 'Teen Wolf: The Movie',
      original_language: 'en',
      original_title: 'Teen Wolf: The Movie',
      overview:
        'The wolves are howling once again, as a terrifying ancient evil emerges in Beacon Hills. Scott McCall, no longer a teenager yet still an Alpha, must gather new allies and reunite trusted friends to fight back against this powerful and deadly enemy.',
      poster_path: '/wAkpPm3wcHRqZl8XjUI3Y2chYq2.jpg',
      media_type: 'movie',
      genre_ids: [28, 14, 10770],
      popularity: 2179.575,
      release_date: '2023-01-18',
      video: false,
      vote_average: 8.4,
      vote_count: 255,
    },
    {
      adult: false,
      backdrop_path: '/qHdPNd1cUaSNYLLNgt1Pv3LVd0T.jpg',
      id: 843794,
      title: 'JUNG_E',
      original_language: 'ko',
      original_title: '정이',
      overview:
        'On an uninhabitable 22nd-century Earth, the outcome of a civil war hinges on cloning the brain of an elite soldier to create a robot mercenary.',
      poster_path: '/z2nfRxZCGFgAnVhb9pZO87TyTX5.jpg',
      media_type: 'movie',
      genre_ids: [878, 28, 12],
      popularity: 2162.848,
      release_date: '2023-01-20',
      video: false,
      vote_average: 6.302,
      vote_count: 199,
    },
    {
      adult: false,
      backdrop_path: '/c9yVIqnrD6fyYhNzNcvAoU6CFG.jpg',
      id: 866413,
      title: 'You People',
      original_language: 'en',
      original_title: 'You People',
      overview:
        'A new couple and their families reckon with modern love amid culture clashes, societal expectations and generational differences.',
      poster_path: '/x5E4TndwASNkaK2hwgeYfsIVo2x.jpg',
      media_type: 'movie',
      genre_ids: [10749, 35],
      popularity: 296.044,
      release_date: '2023-01-20',
      video: false,
      vote_average: 5.9,
      vote_count: 160,
    },
    {
      adult: false,
      backdrop_path: '/mSyQoValhBsJdq3JNGXJww2Q5yL.jpg',
      id: 593643,
      title: 'The Menu',
      original_language: 'en',
      original_title: 'The Menu',
      overview:
        'A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.',
      poster_path: '/fPtUgMcLIboqlTlPrq0bQpKK8eq.jpg',
      media_type: 'movie',
      genre_ids: [27, 53],
      popularity: 230.217,
      release_date: '2022-11-17',
      video: false,
      vote_average: 7.288,
      vote_count: 2094,
    },
    {
      adult: false,
      backdrop_path: '/tt79dbOPd9Z9ykEOpvckttgYXwH.jpg',
      id: 545611,
      title: 'Everything Everywhere All at Once',
      original_language: 'en',
      original_title: 'Everything Everywhere All at Once',
      overview:
        "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
      poster_path: '/rKvCys0fMIIi1X9rmJBxTPLAtoU.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 182.01,
      release_date: '2022-03-24',
      video: false,
      vote_average: 8.042,
      vote_count: 2936,
    },
    {
      adult: false,
      backdrop_path: '/Z0u6taw8aT2gnBDYS6jRjSn6Nv.jpg',
      id: 640146,
      title: 'Ant-Man and the Wasp: Quantumania',
      original_language: 'en',
      original_title: 'Ant-Man and the Wasp: Quantumania',
      overview:
        "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
      poster_path: '/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg',
      media_type: 'movie',
      genre_ids: [12, 878, 35],
      popularity: 161.021,
      release_date: '2023-02-15',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/ogFIG0fNXEYRQKrpnoRJcXQNX9n.jpg',
      id: 619930,
      title: 'Narvik',
      original_language: 'no',
      original_title: 'Kampen om Narvik',
      overview:
        "April, 1940. The eyes of the world are on Narvik, a small town in northern Norway, a source of the iron ore needed for Hitler's war machine. Through two months of fierce winter warfare, the German leader is dealt with his first defeat.",
      poster_path: '/gU4mmINWUF294Wzi8mqRvi6peMe.jpg',
      media_type: 'movie',
      genre_ids: [10752, 18, 36, 28],
      popularity: 1726.752,
      release_date: '2022-12-25',
      video: true,
      vote_average: 7.119,
      vote_count: 113,
    },
    {
      adult: false,
      backdrop_path: '/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
      id: 361743,
      title: 'Top Gun: Maverick',
      original_language: 'en',
      original_title: 'Top Gun: Maverick',
      overview:
        'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
      poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
      media_type: 'movie',
      genre_ids: [28, 18],
      popularity: 369.079,
      release_date: '2022-05-24',
      video: false,
      vote_average: 8.3,
      vote_count: 5895,
    },
    {
      adult: false,
      backdrop_path: '/1vXD5HXqkhvsXFHE7KmCPZGPR1e.jpg',
      id: 674324,
      title: 'The Banshees of Inisherin',
      original_language: 'en',
      original_title: 'The Banshees of Inisherin',
      overview:
        'Two lifelong friends find themselves at an impasse when one abruptly ends their relationship, with alarming consequences for both of them.',
      poster_path: '/dpeR3ue0Q93Rk8jhE2DzVPMRGIm.jpg',
      media_type: 'movie',
      genre_ids: [18, 35],
      popularity: 151.61,
      release_date: '2022-10-21',
      video: false,
      vote_average: 7.459,
      vote_count: 738,
    },
    {
      adult: false,
      backdrop_path: '/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg',
      id: 661374,
      title: 'Glass Onion: A Knives Out Mystery',
      original_language: 'en',
      original_title: 'Glass Onion: A Knives Out Mystery',
      overview:
        'World-famous detective Benoit Blanc heads to Greece to peel back the layers of a mystery surrounding a tech billionaire and his eclectic crew of friends.',
      poster_path: '/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg',
      media_type: 'movie',
      genre_ids: [35, 80, 9648],
      popularity: 709.387,
      release_date: '2022-11-23',
      video: false,
      vote_average: 7.098,
      vote_count: 3138,
    },
    {
      adult: false,
      backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
      id: 436270,
      title: 'Black Adam',
      original_language: 'en',
      original_title: 'Black Adam',
      overview:
        'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
      poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
      media_type: 'movie',
      genre_ids: [14, 28, 878],
      popularity: 1094.617,
      release_date: '2022-10-19',
      video: false,
      vote_average: 7.208,
      vote_count: 3996,
    },
    {
      adult: false,
      backdrop_path: '/a4I481szRmycyreQTLrRe4f4YJe.jpg',
      id: 842544,
      title: 'Transfusion',
      original_language: 'en',
      original_title: 'Transfusion',
      overview:
        'Ryan Logan, a former Special Forces operative, is battling to cope with life after the loss of his wife.  He is thrusted into the criminal underworld to keep his only son from being taken from him.',
      poster_path: '/bxh5xCCW9Ynfg6EZJWUkc1zqTnr.jpg',
      media_type: 'movie',
      genre_ids: [80, 53, 18],
      popularity: 760.725,
      release_date: '2023-01-05',
      video: false,
      vote_average: 6.8,
      vote_count: 24,
    },
    {
      adult: false,
      backdrop_path: '/5pMy5LF2JAleBNBtuzizfCMWM7k.jpg',
      id: 653851,
      title: 'Devotion',
      original_language: 'en',
      original_title: 'Devotion',
      overview:
        "The harrowing true story of two elite US Navy fighter pilots during the Korean War. Their heroic sacrifices would ultimately make them the Navy's most celebrated wingmen.",
      poster_path: '/26yQPXymbWeCLKwcmyL8dRjAzth.jpg',
      media_type: 'movie',
      genre_ids: [10752, 36, 18],
      popularity: 1342.628,
      release_date: '2022-11-23',
      video: false,
      vote_average: 7.561,
      vote_count: 206,
    },
    {
      adult: false,
      backdrop_path: '/o0s4XsEDfDlvit5pDRKjzXR4pp2.jpg',
      id: 19995,
      title: 'Avatar',
      original_language: 'en',
      original_title: 'Avatar',
      overview:
        'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
      poster_path: '/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 14, 878],
      popularity: 919.055,
      release_date: '2009-12-15',
      video: false,
      vote_average: 7.567,
      vote_count: 28148,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

Handlebars.registerHelper('addBaseUrl', function (imgPath) {
  return BASEIMGURL + imgPath;
});

Handlebars.registerHelper('takeYearFromDate', function (date) {
  return date ? date.split('-')[0] : 'year n/a';
});

Handlebars.registerHelper('getGenres', function (genresArray) {
  const genres = genresArray.join(',');
  return genres ? genres : 'Genres n/a';
});

console.log(cardMarkup(response.results));
export { cardMarkup };
