import './js/components/add-btn';
import './js/components/card-render';
import './js/components/fetch';
import './js/films-render';
import './js/components/modal';
import './js/components/spinner';
import './js/pagination';
import './js/user-data';
import './js/toggle-theme';
